<?php

return [
    'prescribed_days' => [0, 30, 60, 90],

    'statuses' => [
        'no_due_date' => 'No Due Date',
        'pending' => 'Pending',
        'done' => 'Done',
        'lapsed' => 'Lapsed',
    ],

    'measure_types' => [
        'resolution' => 'Resolution',
        'ordinance' => 'Ordinance',
        'appropriation_ordinance' => 'Appropriation Ordinance',
    ],

    'outcomes' => [
        'Approved',
        'Pending',
        'Valid',
        'Passed',
        'Invalid in whole',
        'Invalid in part',
        'Shelved',
        'Disapproved',
        'Need further investment',
        'Invalid',
        'On shelve',
        'Withdraw',
        'delete',
        'MR Denied',
        'Declared Invalid by Votation',
    ],

    'sender_seeds' => [
        'Abucay',
        'Atty. Reyes',
        'Bagac',
        'Balanga',
        'BM Del Rosario',
        'BM Del Rosario & Valdecañas',
        'BM Espeleta',
        'BM Galicia',
        'BM Gaza',
        'BM Gaza & Galicia',
        'BM Baluyot',
        'BM Serrano',
        'BM Sunga',
        'BM Estanislao',
        'Dinalupihan',
        'Hermosa',
        'Limay',
        'Mariveles',
        'Morong',
        'Orani',
        'Orion',
        'PGO',
        'Pilar',
        'Samal',
        'Solana Solar Beta Inc.',
        'Tieza',
        'VG Cris',
    ],

    'committee_seeds' => [
        'Justice, Human Rights, and Legal Matters',
        'Energy, Water, and Public Utilities',
        'Tourism',
        'Public Information, People’s Power and Participation',
        'Rules, Ethics, and Privileges',
        'Cooperatives',
        'Women, Children, and Gender Development',
        'Social Welfare and Development',
        'Infrastructure',
        'Labor, Manpower, Employment and Government Services',
        'Senior Citizens and Persons With Disability (PWD)',
        'Trade, Commerce and Industry',
        'Peace and Order and Public Safety',
        'Transportation and Communication',
        'Environmental Protection and Natural Resources',
        'Agriculture, Food and Fisheries',
        'Health and Sanitation',
        'Games and Amusement',
        'Education and Culture',
        'Family Development',
        'Housing and Land Use',
        'Finance, Budget, Appropriation, and Ways & Means',
        'Barangay Affairs and Community Development',
        'Youth and Sports Development',
        'Indigenous Cultural Communities',
        'Committee of the Whole',
    ],

    'csv_path' => env('AGENDA_CSV_PATH', base_path('manual/Agenda/Agenda.csv')),
    'csv_links_path' => env('AGENDA_CSV_LINKS_PATH', base_path('oldsp/Agenda3.csv')),
];
