<?php

return [
    'action_taken' => [
        'For File',
        'For Agenda',
        'For Posting',
    ],

    'referral_seeds' => [
        'Committee on Finance',
        'Committee on Housing & Land Utilization',
        'Housing and Land Utilization',
        'Finance, Budget, Appropriations and Ways and Means',
        'Committee on Justice',
        'Committee on Land Use',
        'Committee on Labor & Employment',
        'Committee on Health',
        'Justice, Human Rights and Legal Matters',
        'Labor, Manpower, Employment and Government Service',
        'Committee on Peace & Order',
        'Committee on Housing and Land Utilization',
        'Health',
        'Committee on Transportation & Communication',
        'Committee on Agriculture',
        'Committee on Environmental protection',
        'Peace and Order and Public Safety',
        'Committee on Social Welfare',
        'Committee on Infrastructure',
        'Committee on Transportation',
        'Education and Culture',
        'Social Welfare and Development',
        'Agriculture, Food and Fisheries',
        'Trade, Commerce and Industry',
        'Committee on Tourism',
        'Committee on Education & Culture',
        'Health and Sanitation',
        'Youth and Sports Development',
        'Committee on Trade, Commerce and Industry',
        'Committee on Public Information',
        'Environmental Protection and Natural Resources',
    ],

    'concerned_agencies' => [
        'Accounting',
        'Accounting/Abucay',
        'Budget',
        'Budget/Abucay',
        'Budget/Bagac',
        'Budget/Balanga',
        'Budget/Dinalupihan',
        'Budget/Hermosa',
        'Budget/Limay',
        'Budget/Mariveles',
        'Budget/Morong',
        'Budget/Orani',
        'Budget/Orion',
        'Budget/Pilar',
        'Budget/Samal',
        'City of Balanga',
        'Legal',
        'Mayor/Abucay',
        'Mayor/Bagac',
        'Mayor/Balanga',
        'Mayor/Dinalupihan',
        'Mayor/Hermosa',
        'Mayor/Limay',
        'Mayor/Mariveles',
        'Mayor/Morong',
        'Mayor/Orani',
        'Mayor/Orion',
        'Mayor/Pilar',
        'Mayor/Samal',
        'MIS',
        'PBO',
        'PGENRO',
        'PGSBATAAN',
        'Provincial Accounting',
        'PTO',
        'SB Abucay',
        'SB Bagac',
        'SB Dinalupihan',
        'SB Hermosa',
        'SB Limay',
        'SB Mariveles',
        'SB Morong',
        'SB Orani',
        'SB Orion',
        'SB Pilar',
        'SB Samal',
        'SP',
        'SP Balanga',
        'SP Members',
        'Treasurer/Abucay',
        'Treasurer/Bagac',
        'Treasurer/Balanga',
        'Treasurer/Dinalupihan',
        'Treasurer/Hermosa',
        'Treasurer/Limay',
        'Treasurer/Mariveles',
        'Treasurer/Morong',
        'Treasurer/Orani',
        'Treasurer/Orion',
        'Treasurer/Pilar',
        'Treasurer/Samal',
        'Vice-Gov',
    ],
];
